version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: meu-postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - minha-rede
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: tasklist
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - CHAVEDB=postgres://postgres:1234@db:5432/meu-postgres-db
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  postgres_data: {}


